[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
# logfile=/var/log/supervisor/supervisord.log
logfile=/dev/stdout
logfile_maxbytes=0
# childlogdir=/var/log/supervisor

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# ORDER OF STARTUP:
# =================
# Display Server  - priority 5
# OLED Controller - priority 10
# Action Manager  - priority 20
# Web Manager     - priority 30

# === Display Server ===
[program:fitebox_display]
command=/usr/bin/python3 /app/fitebox_display.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/fitebox/log/fitebox_display.err.log
stdout_logfile=/fitebox/log/fitebox_display.out.log
environment=PYTHONUNBUFFERED="1"
stopsignal=TERM
stopwaitsecs=10
priority=5

# === OLED Controller ===
[program:oled_controller]
command=/usr/bin/python3 /app/oled_controller.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/fitebox/log/oled_controller.err.log
stdout_logfile=/fitebox/log/oled_controller.out.log
environment=PYTHONUNBUFFERED="1"
stopsignal=TERM
stopwaitsecs=10
priority=10

# === Action Manager ===
[program:fitebox_manager]
command=/usr/bin/python3 /app/fitebox_manager.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/fitebox/log/fitebox_manager.err.log
stdout_logfile=/fitebox/log/fitebox_manager.out.log
environment=PYTHONUNBUFFERED="1"
stopsignal=TERM
stopwaitsecs=10
priority=20

# === Web manager ===
[program:fitebox_web]
command=/usr/bin/python3 -m uvicorn fitebox_web:app --host 0.0.0.0 --port 8080 --no-access-log
directory=/app/web
autostart=true
autorestart=true
startretries=5
startsecs=3
redirect_stderr=true
stdout_logfile=/fitebox/log/fitebox_web.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
environment=PYTHONUNBUFFERED="1"
stopsignal=TERM
stopwaitsecs=10
priority=30
