[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
# logfile=/var/log/supervisor/supervisord.log
logfile=/dev/stdout
logfile_maxbytes=0
# childlogdir=/var/log/supervisor

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# === OLED Controller ===
[program:oled_controller]
# command=/usr/bin/python3 /app/oled_controller.py
command=make -C /app oled_controller
directory=/tmp
autostart=true
autorestart=true
stderr_logfile=/fitebox/log/oled_controller.err.log
stdout_logfile=/fitebox/log/oled_controller.out.log
priority=10
# OLED controller has the highest priority (10) to ensure it starts before the manager and web server.

# === Action Manager ===
[program:fitebox_manager]
command=make -C /app fitebox_manager
directory=/tmp
autostart=true
autorestart=true
stderr_logfile=/fitebox/log/fitebox_manager.err.log
stdout_logfile=/fitebox/log/fitebox_manager.out.log
priority=20
# Manager starts after OLED (higher priority)

# === Web manager ===
[program:fitebox_web]
command=make web
directory=/app/web
autostart=true
autorestart=true
startretries=5
startsecs=3
redirect_stderr=true
stdout_logfile=/fitebox/log/fitebox_web.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
environment=PYTHONUNBUFFERED="1"
priority=30
# Web manager depends on both OLED and Manager, so it has the lowest priority (30) to ensure they start first.
